FROM nvcr.io/nvidia/tensorflow:24.01-tf2-py3

RUN \
     pip install pandas==2.1.4 && \
     pip install scikit-learn==1.4.2 && \
     pip install matplotlib && \
     pip install jupyterlab nbformat

